package fr.arinonia.valkyria.launcher.files;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.util.Properties;

/**
 * Created by Arinonia on 28/06/2020 inside the package - fr.arinonia.valkyria.launcher.files
 */
public class Saver {

    private final File file;
    private final Properties properties;

    public Saver(File file) {
        this.file = file;
        this.properties = new Properties();

        if (file.exists())
            load();
    }

    public void set(String key, String value) {
        properties.setProperty(key, value);
        save();
    }
    public String get(String key) {
        return properties.getProperty(key);
    }

    public String get(String key, String def) {
        String value = properties.getProperty(key);
        return value == null ? def : value;
    }

    public void save() {
        try {
            properties.store(new BufferedWriter(new FileWriter(file)), "Generated by the OpenLauncherLib Saver");
        } catch (Throwable t) {
            throw new RuntimeException("Can't save the properties", t);
        }
    }

    public void load() {
        try {
            properties.load(new FileInputStream(file));
        }
        catch (Throwable t) {
            throw new RuntimeException("Can't load the properties", t);
        }
    }
}

